### PR TITLE
Renaming plugins to be org.zowe

### PR DESCRIPTION
**Pull request by 1000TurquoisePogs**
Signed-off-by: Sean Grady <sgrady@rocketsoftware.com>

### CODE REVIEW

**Review by rpenny125 — CHANGES_REQUESTED** [review]
Seems like this change could break file-transfer-app:

image

**Comment by 1000TurquoisePogs** [comment]
Here's the fix for that: https://github.com/zowe/file-transfer-app/pull/7

**Review by rpenny125 — APPROVED** [review]
Changes looks safe. I couldn't finish the test due to self-signed certificate:
```
{ Error: self signed certificate in certificate chain
    at TLSSocket.<anonymous> (_tls_wrap.js:1105:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:639:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:469:38) code: 'SELF_SIGNED_CERT_IN_CHAIN' }```

However, the fact that I got that far is a good sign.

**Comment by 1000TurquoisePogs** [comment]
For future reference, you can get by this by using this on the command line: "--allowInvalidTLSProxy=true"

**Pull request merged**
